created command build_gh_release that pulls release notes and version…
ondewo/ondewo-nlu-client-python pull request #60
Opened 2022-07-12 11:56 UTC by ahasanovicc

… from RELEASE.md

2022-07-14 15:58 UTC, teddius requested changes
Looks good! 

In order to make everything through docker not requiring an installation of gh tools, I suggest that you create a docker file in which you install the gh tools and then in the make target run this docker image with a mapped in volume and the gh release command.

Have a look how we do it with pushing code to pypi . You basically can copy most of this docker image building code in Docker file.pypi and create Dockerimage.github.

2022-07-19 12:57 UTC, MaxWolf-01 approved these changes

2022-07-19 13:06 UTC, foldvaridominic commented on Makefile
> +export GH_TOKEN=
Just note (to myself mostly):
Line 2 is necessary I guess to access these env variables in the docker make commands.
Line 3 is just workaround I guess for the gh login command, and it is not possible to get rid of it.

2022-07-19 13:06 UTC, foldvaridominic approved these changes
Nice

2022-07-19 13:12 UTC, merged